name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build Web Version
        run: npx expo export
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: malika-vault-files
          path: dist/

        
